/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/router/__root'
import { Route as IndexRouteImport } from './app/router/index'
import { Route as DashboardEnrollmentRouteImport } from './app/router/dashboard/enrollment'
import { Route as DashboardRectoriaIndexRouteImport } from './app/router/dashboard/rectoria/index'
import { Route as DashboardBandIndexRouteImport } from './app/router/dashboard/band/index'
import { Route as DashboardStudentIdEnrollmentRouteImport } from './app/router/dashboard/student/$id/enrollment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEnrollmentRoute = DashboardEnrollmentRouteImport.update({
  id: '/dashboard/enrollment',
  path: '/dashboard/enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRectoriaIndexRoute = DashboardRectoriaIndexRouteImport.update({
  id: '/dashboard/rectoria/',
  path: '/dashboard/rectoria/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBandIndexRoute = DashboardBandIndexRouteImport.update({
  id: '/dashboard/band/',
  path: '/dashboard/band/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentIdEnrollmentRoute =
  DashboardStudentIdEnrollmentRouteImport.update({
    id: '/dashboard/student/$id/enrollment',
    path: '/dashboard/student/$id/enrollment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/enrollment': typeof DashboardEnrollmentRoute
  '/dashboard/band/': typeof DashboardBandIndexRoute
  '/dashboard/rectoria/': typeof DashboardRectoriaIndexRoute
  '/dashboard/student/$id/enrollment': typeof DashboardStudentIdEnrollmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/enrollment': typeof DashboardEnrollmentRoute
  '/dashboard/band': typeof DashboardBandIndexRoute
  '/dashboard/rectoria': typeof DashboardRectoriaIndexRoute
  '/dashboard/student/$id/enrollment': typeof DashboardStudentIdEnrollmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/enrollment': typeof DashboardEnrollmentRoute
  '/dashboard/band/': typeof DashboardBandIndexRoute
  '/dashboard/rectoria/': typeof DashboardRectoriaIndexRoute
  '/dashboard/student/$id/enrollment': typeof DashboardStudentIdEnrollmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/enrollment'
    | '/dashboard/band/'
    | '/dashboard/rectoria/'
    | '/dashboard/student/$id/enrollment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/enrollment'
    | '/dashboard/band'
    | '/dashboard/rectoria'
    | '/dashboard/student/$id/enrollment'
  id:
    | '__root__'
    | '/'
    | '/dashboard/enrollment'
    | '/dashboard/band/'
    | '/dashboard/rectoria/'
    | '/dashboard/student/$id/enrollment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardEnrollmentRoute: typeof DashboardEnrollmentRoute
  DashboardBandIndexRoute: typeof DashboardBandIndexRoute
  DashboardRectoriaIndexRoute: typeof DashboardRectoriaIndexRoute
  DashboardStudentIdEnrollmentRoute: typeof DashboardStudentIdEnrollmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/enrollment': {
      id: '/dashboard/enrollment'
      path: '/dashboard/enrollment'
      fullPath: '/dashboard/enrollment'
      preLoaderRoute: typeof DashboardEnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/rectoria/': {
      id: '/dashboard/rectoria/'
      path: '/dashboard/rectoria'
      fullPath: '/dashboard/rectoria/'
      preLoaderRoute: typeof DashboardRectoriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/band/': {
      id: '/dashboard/band/'
      path: '/dashboard/band'
      fullPath: '/dashboard/band/'
      preLoaderRoute: typeof DashboardBandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student/$id/enrollment': {
      id: '/dashboard/student/$id/enrollment'
      path: '/dashboard/student/$id/enrollment'
      fullPath: '/dashboard/student/$id/enrollment'
      preLoaderRoute: typeof DashboardStudentIdEnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardEnrollmentRoute: DashboardEnrollmentRoute,
  DashboardBandIndexRoute: DashboardBandIndexRoute,
  DashboardRectoriaIndexRoute: DashboardRectoriaIndexRoute,
  DashboardStudentIdEnrollmentRoute: DashboardStudentIdEnrollmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
