/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/router/__root'
import { Route as LoginRouteImport } from './app/router/login'
import { Route as LayoutRouteImport } from './app/router/_layout'
import { Route as IndexRouteImport } from './app/router/index'
import { Route as DashboardBandIndexRouteImport } from './app/router/dashboard/band/index'
import { Route as LayoutDashboardIndexRouteImport } from './app/router/_layout.dashboard.index'
import { Route as LayoutDashboardEnrollmentRouteImport } from './app/router/_layout.dashboard.enrollment'
import { Route as LayoutDashboardStudentIdEnrollmentRouteImport } from './app/router/_layout.dashboard.student.$id.enrollment'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBandIndexRoute = DashboardBandIndexRouteImport.update({
  id: '/dashboard/band/',
  path: '/dashboard/band/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDashboardIndexRoute = LayoutDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardEnrollmentRoute =
  LayoutDashboardEnrollmentRouteImport.update({
    id: '/dashboard/enrollment',
    path: '/dashboard/enrollment',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDashboardStudentIdEnrollmentRoute =
  LayoutDashboardStudentIdEnrollmentRouteImport.update({
    id: '/dashboard/student/$id/enrollment',
    path: '/dashboard/student/$id/enrollment',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/enrollment': typeof LayoutDashboardEnrollmentRoute
  '/dashboard/': typeof LayoutDashboardIndexRoute
  '/dashboard/band/': typeof DashboardBandIndexRoute
  '/dashboard/student/$id/enrollment': typeof LayoutDashboardStudentIdEnrollmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/enrollment': typeof LayoutDashboardEnrollmentRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/dashboard/band': typeof DashboardBandIndexRoute
  '/dashboard/student/$id/enrollment': typeof LayoutDashboardStudentIdEnrollmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/dashboard/enrollment': typeof LayoutDashboardEnrollmentRoute
  '/_layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/dashboard/band/': typeof DashboardBandIndexRoute
  '/_layout/dashboard/student/$id/enrollment': typeof LayoutDashboardStudentIdEnrollmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/enrollment'
    | '/dashboard/'
    | '/dashboard/band/'
    | '/dashboard/student/$id/enrollment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/enrollment'
    | '/dashboard'
    | '/dashboard/band'
    | '/dashboard/student/$id/enrollment'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/dashboard/enrollment'
    | '/_layout/dashboard/'
    | '/dashboard/band/'
    | '/_layout/dashboard/student/$id/enrollment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  DashboardBandIndexRoute: typeof DashboardBandIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/band/': {
      id: '/dashboard/band/'
      path: '/dashboard/band'
      fullPath: '/dashboard/band/'
      preLoaderRoute: typeof DashboardBandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutDashboardIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/enrollment': {
      id: '/_layout/dashboard/enrollment'
      path: '/dashboard/enrollment'
      fullPath: '/dashboard/enrollment'
      preLoaderRoute: typeof LayoutDashboardEnrollmentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/student/$id/enrollment': {
      id: '/_layout/dashboard/student/$id/enrollment'
      path: '/dashboard/student/$id/enrollment'
      fullPath: '/dashboard/student/$id/enrollment'
      preLoaderRoute: typeof LayoutDashboardStudentIdEnrollmentRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutDashboardEnrollmentRoute: typeof LayoutDashboardEnrollmentRoute
  LayoutDashboardIndexRoute: typeof LayoutDashboardIndexRoute
  LayoutDashboardStudentIdEnrollmentRoute: typeof LayoutDashboardStudentIdEnrollmentRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardEnrollmentRoute: LayoutDashboardEnrollmentRoute,
  LayoutDashboardIndexRoute: LayoutDashboardIndexRoute,
  LayoutDashboardStudentIdEnrollmentRoute:
    LayoutDashboardStudentIdEnrollmentRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  DashboardBandIndexRoute: DashboardBandIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
